# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  - group: azuresubscription
  - name: 'keyvault_name'
    value: 'acme$(ENV)tfstate$(REGION_SHORT)vault' 
  - name: 'tf_backend_storage_name'
    value: 'acme$(ENV)tfstate$(REGION_SHORT)stor' 

stages:
  - stage: Dev
    variables:
      ENV: 'dev'
      REGION: 'northeurope'
      REGION_SHORT: 'eun'
    jobs:
      - job: SetUpTerraformRemoteBackend
        displayName: 'Set up Terraform remote backend'
        steps:
          - task: AzureCLI@2
            displayName: 'Run script to set up remote backend'
            inputs:
              scriptPath: './create-tf-backend.sh'
              azureSubscription: 'TF-Serviceconnection'
              scriptType: bash
          - task: TerraformInstaller@0
            inputs:
              terraformVersion: '0.12.20'
            displayName: Install Terraform
          - task: AzureKeyVault@1
            displayName: 'Retrieve TF backend storage access key from Key Vault'
            inputs:
              azureSubscription: 'TF-Serviceconnection'
              KeyVaultName: $(keyvault_name)
              SecretsFilter: 'tfstatestorkey'
          - task: TerraformCLI@0
            displayName: "Terraform Init"
            inputs:
              command: 'init'
              workingDirectory: '$(System.DefaultWorkingDirectory)/terraform'
              commandOptions: '-backend-config="access_key=$(tfstatestorkey)" -backend-config="storage_account_name=$(tf_backend_storage_name)" -backend-config="container_name=tfstate" -backend-config="key=tfstate.key"'
          - task: TerraformCLI@0
            displayName: "Terraform Validate"
            inputs:
              command: 'validate'
              workingDirectory: '$(System.DefaultWorkingDirectory)/terraform'
          - task: TerraformCLI@0
            displayName: "Terraform Apply"
            inputs:
              command: 'apply'
              workingDirectory: '$(System.DefaultWorkingDirectory)/terraform'
              commandOptions: '--auto-approve'
              environmentServiceName: 'TF-Serviceconnection'
        
